### ISSUE TITLE
Pane component?

### ISSUE THREAD

**Issue by HybridFox** [a-ui/core_branding_scss#113]
A overlay & z-index is provided for a possible pane component.
So i was wondering if it is possible to create a pane component with the existing styles?

**Comment by TriangleJuice** [comment]
Hi @HybridFox, thanks for the suggestion! Not sure if you know this, but there's already a pane component present in the accompanying [ACPaaS UI library](https://github.com/digipolisantwerp/acpaas-ui_angular/tree/master/packages/layout/src/lib/pane).

However, keep in mind that we are currently very busy updating the documentation, so if you need help don't hesitate to [contact us](https://github.com/digipolisantwerp/acpaas-ui_angular/blob/master/README.md#questions). We hope to finish it the documentation the end of the month.

**Comment by tom-odb** [comment]
We know there is a component in the angular library, we need it in react.
Since there are some traces of the pane in the core branding, we were wondering if there are any plans to incorporate this component in the core branding?
If that is not the case,  are we supposed to use the `aui-kit` then or do we add the styling in each framework that implements the pane?

**Comment by TriangleJuice** [comment]
Oh, I see. The AUI kit will be part of the Core Branding probably by the end of september.
